### ISSUE TITLE
Add support for Files

### ISSUE THREAD

**Issue by mikker** [sandro/ephemeral_response#2]
I'm testing image uploading which, I guess, isn't supported by ephemeral_response? I'd sure like it to be :)

Stack trace:

<pre>

TypeError: can't dump File
    /Users/mikker/.rvm/gems/ruby-1.9.2-p0@3frames/gems/ephemeral_response-0.3.2/lib/ephemeral_response/fixture.rb:120:in `dump'
    /Users/mikker/.rvm/gems/ruby-1.9.2-p0@3frames/gems/ephemeral_response-0.3.2/lib/ephemeral_response/fixture.rb:120:in `deep_dup'
    /Users/mikker/.rvm/gems/ruby-1.9.2-p0@3frames/gems/ephemeral_response-0.3.2/lib/ephemeral_response/fixture.rb:56:in `initialize'
    /Users/mikker/.rvm/gems/ruby-1.9.2-p0@3frames/gems/ephemeral_response-0.3.2/lib/ephemeral_response/fixture.rb:15:in `new'
    /Users/mikker/.rvm/gems/ruby-1.9.2-p0@3frames/gems/ephemeral_response-0.3.2/lib/ephemeral_response/fixture.rb:15:in `find'
    /Users/mikker/.rvm/gems/ruby-1.9.2-p0@3frames/gems/ephemeral_response-0.3.2/lib/ephemeral_response/fixture.rb:31:in `find_or_initialize'
    /Users/mikker/.rvm/gems/ruby-1.9.2-p0@3frames/gems/ephemeral_response-0.3.2/lib/ephemeral_response/fixture.rb:43:in `respond_to'
    /Users/mikker/.rvm/gems/ruby-1.9.2-p0@3frames/gems/ephemeral_response-0.3.2/lib/ephemeral_response/net_http.rb:26:in `request'
    /Users/mikker/.rvm/gems/ruby-1.9.2-p0@3frames/gems/aws-s3-0.6.2/lib/aws/s3/connection.rb:45:in `block in request'
</pre>

**Comment by sandro** [comment]
Interesting. How are you uploading images? Are you using a library or simply Net::HTTP? Can you provide a snippet of the upload code?

**Comment by mikker** [comment]
Using Paperclip to S3, Factory Girl and Rails' `fixture_file_upload`.

<pre>
Factory.define(:animation) do |a|
  a.association :user
  a.image { fixture_file_upload("test_animation.gif", 'image/gif') }
end
</pre>

**Comment by mikker** [comment]
As a little over 4 years had gone by and everyone but Github had forgotten about this, @mikker thought he'd close the issue and let the wretched machine feel the joy of letting go.
